title: Default


icon: info
image:
  query: false
  back: blue-200


columns:
  # main content
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Text
            type: textarea

          
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
      files:
        type: files

