title: Index Journal

tabs:
  issues:
    icon: pen
    sections:
      issues:
        type: pages
        parent: kirby.page("issues")
        template: issue

  pages:
    icon: page
    sections:
      pages:
        label: Main Pages
        status: all
        sort: num

  footer:
    sections:
      footer:
        type: fields
        fields:
          footer:
            type: pages
            query: 
  
  admin:
    icon: settings
    sections:
      admin:
        type: fields
        fields:
          janitor_thumbssite:
            type: janitor
            command: 'janitor:thumbs --site'
            label:  Thumbs
            icon: images

          
          crossref_section:
            type: headline
            label: Crossref Settings

          crossref_username:
            label: Username
            type: text
            width: 1/2

          crossref_password:
            label: Password
            type: text
            width: 1/2

          crossref_prefix:
            label: DOI Prefix
            type: text
            help: e.g. 10.38030

          crossref_issn:
            label: ISSN
            type: text
            width: 1/2

          crossref_journalTitle:
            label: Journal Title
            type: text
            width: 1/2

          crossref_apiUrl:
            label: API Endpoint
            type: url
            default: https://api.crossref.org/v2/deposits

          doaj_section:
            type: headline
            label: DOAJ Settings

          doaj_apiKey:
            label: API Key
            type: text
            width: 1/2

          doaj_apiUrl:
            label: API Endpoint
            type: url
            default: https://doaj.org/api/articles

          doaj_bulkApiUrl:
            label: Bulk API Endpoint
            type: url
            default: https://doaj.org/api/v4/bulk/articles
          
#  seotab: seo
  seo: seo/site
